DateLocalisationExample/Controllers/LocalDatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DateExample.DataModel;

namespace DateLocalisationExample.Controllers
{
    public class LocalDatesController : Controller
    {
        private Week11Context db = new Week11Context();

        // GET: LocalDates
        public ActionResult Index()
        {
            return View(db.Dates.ToList());
        }

        // GET: LocalDates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LocalDate localDate = db.Dates.Find(id);
            if (localDate == null)
            {
                return HttpNotFound();
            }
            return View(localDate);
        }

        // GET: LocalDates/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LocalDates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,StartDate,EndDate")] LocalDate localDate)
        {
            if (ModelState.IsValid)
            {
                db.Dates.Add(localDate);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(localDate);
        }

        // GET: LocalDates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LocalDate localDate = db.Dates.Find(id);
            if (localDate == null)
            {
                return HttpNotFound();
            }
            return View(localDate);
        }

        // POST: LocalDates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,StartDate,EndDate")] LocalDate localDate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(localDate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(localDate);
        }

        // GET: LocalDates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LocalDate localDate = db.Dates.Find(id);
            if (localDate == null)
            {
                return HttpNotFound();
            }
            return View(localDate);
        }

        // POST: LocalDates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LocalDate localDate = db.Dates.Find(id);
            db.Dates.Remove(localDate);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DateLocalisationExample/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DateExample.DataModel;
using PagedList;

namespace DateLocalisationExample.Controllers
{
    public class StudentsController : Controller
    {
        private Week11Context db = new Week11Context();

        // GET: Students
        public ActionResult Index(string sort, string search, int? page)
        {
            ViewBag.SnameSort = String.IsNullOrEmpty(sort) ? "sname_desc" : string.Empty;
            ViewBag.FnameSort = sort == "fname" ? "fname_desc" : "fname";

            ViewBag.CurrentSearch = search;
            IQueryable<Student> students = db.Students;

            if (!String.IsNullOrEmpty(search))
            {
                students = students.Where(
                    s => s.Firstname.StartsWith(search) || s.Surname.StartsWith(search));
            }
            switch (sort)
            {
                case "sname_desc":
                    students = students.OrderByDescending(s => s.Surname).ThenBy(s => s.Firstname);
                    break;
                case "fname":
                    students = students.OrderBy(s => s.Firstname).ThenBy(s => s.Surname);
                    break;
                case "fname_desc":
                    students = students.OrderByDescending(s => s.Firstname).ThenBy(s => s.Surname);
                    break;
                default:
                    students = students.OrderBy(s => s.Surname).ThenBy(s => s.Firstname);
                    break;
            }

            int pageSize = 10;
            int pageNumber = page ?? 1;

            return View(students.ToPagedList(pageNumber, pageSize));
        }

        // GET: Students/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentNumber,Firstname,Surname,DateRegistered")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(student);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentNumber,Firstname,Surname,DateRegistered")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DateLocalisationExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IT Sligo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/themes/base/all.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
            </div>
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("About", "About", "Home", new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Date", "Index", "LocalDates", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Student", "Index", "Students", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        //$(function () { // will trigger when the document is ready
        //   $('.date-picker').datepicker({
        //            dateFormat: 'dd-M-yy'
        //        }

        //); //Initialise any date pickers
        //});
        </script>
</body>
</html>